### PR TITLE
Adds the ability to install late binding apt-get packages

### PR DESCRIPTION
**Pull request by RussellRollins**
The ONBUILD functionality of the Sentry onpremise Docker image is really awesome. It's very convenient to be able to add late binding pip requirements.

Unfortunately, many pip requirements require additional apt-get requirements. In my concrete use case, the sentry-ldap-auth plugin requires 3 additional packages to be installed.

Before:

```
~/Code/onpremise - git@(master) $ cat requirements.txt
# Add plugins here
sentry-ldap-auth

~/Code/onpremise - git@(master) $ docker-compose build
Building base
Step 1/1 : FROM sentry:8.22-onbuild
# Executing 4 build triggers
[snip]
    In file included from Modules/LDAPObject.c:8:0:
    Modules/constants.h:7:18: fatal error: lber.h: No such file or directory
     #include "lber.h"
                      ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

My PR introduces a new file to the build system, `requirements.system`. All packages specified in it are installed before the pip installation of those specified in `requirements.txt`.

After:

```
~/Code/onpremise - git@(master) $ cat Dockerfile
FROM russell-onbuild-fork

~/Code/onpremise - git@(master) $ cat requirements.txt
# Add plugins here
sentry-ldap-auth

~/Code/onpremise - git@(master) $ cat requirements.system
# Add plugin system requirements here
libsasl2-dev
libldap2-dev
libssl-dev

~/Code/onpremise - git@(master) $ docker-compose build
Building base
Step 1/1 : FROM russell-onbuild-fork
# Executing 5 build triggers
[snip]
Successfully built 8976e697e406
Successfully tagged onpremise_web:latest
```

There are checks for no `requirements.system` file, or for one with only comments (to prevent extraneous apt-get updates which can slow down builds for users who don't need this functionality). The workaround is relatively simple (just abandon the ONBUILD functionality and install pip + apt-get requirements in your own Dockerfile), but I thought it'd be cool to make it possible for everyone to take advantage of the easy configuration you worked on.

### CODE REVIEW

**Comment by ArcticSnowman** [comment]
You also need to apply this to the 9.0 Dockerfile

**Comment by RussellRollins** [comment]
Thanks for the suggestion @ArcticSnowman !

**Comment by mattrobenolt** [comment]
Hey @RussellRollins, sorry for the delay here.

What about if we supported a generic `init.d/*` directory or something like that, rather than explicitly an apt-install list of files? If we have a generic hook, then it'd be possible for you to just add your own `apt-get install` into that and would leave things flexible for whatever else people may want to do.

My inspiration for this is how Postgres does it. Postgres needs to support hooks from within the entrypoint, which is slightly different than here, but same idea applies.

Something like: https://github.com/docker-library/postgres/blob/master/9.6/docker-entrypoint.sh#L132

What do you think?

**Comment by jk** [comment]
@RussellRollins Any news on this? Today I went into the exact same issue with the LDAP plugin. Searching GitHub, I see every one work around this issue by not using the onbuild feature and instead clone this repo (instead of https://github.com/getsentry/onpremise) and add their apt-get dependencies there. I'll do the same.

Instead of over complicate the discussion, I suggest, modifying this PR to reflect the repo changes for 9.1. Accept it and afterwards be open for contributions, if someone wants to implement @mattrobenolt Postgres suggestion.

**Comment by RussellRollins** [comment]
@jk in my opinion, Matt's suggestion is both more flexible and simpler than mine (mostly, adding the non-standard `requirements.system` file here seems messy) and probably should be how this is solved. Although I agree with your sentiment that accepting this as is and being open for contributions would be a more iterative approach, there would then be an obligation not to break backwards compatibility for folks using my silly `requirements.system` file.

I no longer work on a Dockerized Sentry in my day job, so I'd need to take this over the finish line in my free time. I can probably get back to this soon, to be honest I had mostly forgotten about it. We solved the issue in the same way (cloning `onpremise` and writing our own Docker build) and it stopped being a real pain point.

**Comment by BYK** [comment]
@RussellRollins this looks useful and interesting and I'd be happy to help you finish it off the way @mattrobenolt suggested when you have the time :)

**Comment by BYK** [comment]
Closing due to staleness and this repo getting archived (contents now live under https://github.com/getsentry/sentry/tree/master/docker)

**Pull request closed without merging**
