### PR TITLE
Add Env parameter to allow Register

### PR DESCRIPTION
**Pull request by mathieu-gilloots**
This PR goal is to allow or not the registration through the docker environnement parameter.
True per default.

### CODE REVIEW

**Comment by mathieu-gilloots** [comment]
@mattrobenolt for Review

**Comment by rwky** [comment]
There are now three PRs for this #100 #97 #92 it'd be great if one of them could get merged.

**Comment by denji** [comment]
#### `sentry/sentry.conf.py` (SENTRY_ALLOW_REGISTER)

    cd sentry/
    curl -o sentry.conf.py https://raw.githubusercontent.com/getsentry/docker-sentry/c73e82b/8.14/sentry.conf.py
    curl -sL https://github.com/getsentry/docker-sentry/pull/100.diff | patch -p2

#### `sentry/sentry.env`

    SENTRY_ALLOW_REGISTER=False

#### `sentry/docker-compose.yml`

    sentry:
      image: sentry
      env_file:
       - ./sentry.env
      volumes:
       - ./sentry.conf.py:/etc/sentry/sentry.conf.py:ro

**Comment by mattrobenolt** [comment]
I'm closing this because this request is silly. Just edit the config file and do whatever you want. Environment variables are not intended to replace 100% of configuration. Things like this belong in a config file. Things like connection information is more suitable.

**Pull request closed without merging**
