### PR TITLE
disable registration by default

### PR DESCRIPTION
**Pull request by julianuphoff**
[https://github.com/getsentry/sentry/issues/5617](https://github.com/getsentry/sentry/issues/5617)
[https://github.com/getsentry/sentry/pull/5328](https://github.com/getsentry/sentry/pull/5328)

### CODE REVIEW

**Comment by dcramer** [comment]
As I said in the ticket, this is not acceptable behavior.

**Comment by tarabanton** [comment]
Maybe it's better to replace with something configurable like
```
...
###########
# General #
###########

# Enable register feature
SENTRY_FEATURES['auth:register'] = env('SENTRY_AUTH_REGISTER', False)
...
```

**Comment by dcramer** [comment]
This is resolved in master and configurable via the UI

**Comment by kwiesmueller** [comment]
Is it? I still can not find the setting, when do you think this will make it onto stable dockerhub?

**Comment by mattrobenolt** [comment]
We release new versions the 1st week of the month.

**Comment by kwiesmueller** [comment]
ok, thanks...
will stick to a custom command till then, good work fixing this so quickly
```
command:
        - /bin/bash
        - -c
        - egrep -q "auth:register.*False" /etc/sentry/sentry.conf.py || echo "SENTRY_FEATURES['auth:register'] = False" >> /etc/sentry/sentry.conf.py; /entrypoint.sh run web
```

**Pull request closed without merging**
