### PR TITLE
Make user registration configurable by ENV var

### PR DESCRIPTION
**Pull request by dpattmann**
I would like to disable the user registration so I add this small line of code to do this via an ENV variable.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
@dpattmann I think I'd rather enable the whole `SENTRY_FEATURES` instead of individual things like this.

What if there were a `SENTRY_FEATURES=auth:register,foo:bar` env var instead?

**Comment by LoicMahieu** [comment]
I agree with @mattrobenolt . It would be great to allow us to customize any sentry features :+1:

**Comment by dpattmann** [comment]
@mattrobenolt  & @LoicMahieu I would prefer a solution with one ```SENTRY_FEATURES``` variable too. Can we implement this feature without breaking running configurations?

**Comment by Jastrzebowski** [comment]
I agree with @dpattmann in fact `SENTRY_OPTIONS` is treated the same way as proposed in this PR with features.

**Comment by mattrobenolt** [comment]
I'm closing this out because we're not going to be pursuing this direction. New documentation for 8.6 is going to reflect better ways of achieving this without using environment variables.

**Comment by simpleton** [comment]
@mattrobenolt sorry for interrupt, I didn't find the better way you mentioned which had released in 8.6. Could you paste a link here?

**Comment by mattrobenolt** [comment]
@simpleton the better way is to just supply your own configuration file and not use environment variables. https://github.com/getsentry/onpremise has been put together to help facilitate doing that easier and should be the foundation for deploying.

**Pull request closed without merging**
