### PR TITLE
Allow to use multi organization mode from Dockerfile

### PR DESCRIPTION
**Pull request by sroze**
This PR simply adds the ability to use the `SENTRY_MULTI_ORGANIZATION` environment variable with a value `yes` to explicitly activate the multi organisation mode.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
What if we exposed

`SENTRY_SINGLE_ORGANIZATION` and the value could be `1` or `0`? But we bake into the `Dockerfile` `ENV SENTRY_SINGLE_ORGANIZATION 1` by default?

This way the name matches the setting, and we use `1`/`0` for other things indicating booleans.

**Comment by mattrobenolt** [comment]
I'd rather this be added here: https://github.com/getsentry/docker-sentry/blob/master/8.0/Dockerfile#L11-L12

**Comment by mattrobenolt** [comment]
I'll get this in for 8.1

**Comment by sroze** [comment]
@mattrobenolt yep, we can set a default value directly in the Dockerfile, that definitely makes sense. Also, I agree with you regarding the name of the environment variable. I'll update the PR asap!

**Comment by mattrobenolt** [comment]
If you're going to update it, make sure to use the new `sentry.utils.types` from the commits referenced here. Or just wait, and I'll take care of it. :)

**Comment by sroze** [comment]
I let you deal with it then :)

**Comment by mattrobenolt** [comment]
@sroze Addressed with 134bde3, this provides `SENTRY_SINGLE_ORGANIZATION` env var, which you can set to any "falsey" value, like, `0`, `false`, or `no`.

**Comment by mattrobenolt** [comment]
Also, this requires 8.1 which will be released today, it can't be backported for 8.0.x/

**Pull request closed without merging**
